### ISSUE TITLE
EDMC 3.50 Support?

### ISSUE THREAD

**Issue by Elite-IGAU** [sagittarius-eye/edmc-sagi#1]
Does this plugin support the Python 2 (3.43) and Python 3 (3.50) versions of EDMC? 

Python 2 officially died on Jan 1st, 2020.

**Comment by Lutonite** [comment]
Yep this supports both, since most people still have EDMC 3.43 with Python 2 I wanted to support both.

Once 3.50 goes official I guess I'll put a warning to upgrade in the settings page of the plugin, and then I'll discontinue the Python 2 support.
